import { Geist, Geist_Mono, Quicksand } from "next/font/google";
import "./globals.css";
import AdvertiseHeader from "../../components/advertiseHeader/AdvertiseHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-quicksand",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${quicksand.variable} antialiased relative selection:bg-yesil overflow-hidden`}
      >
        <AdvertiseHeader />
        {children}
      </body>
    </html>
  );
}
